### ISSUE TITLE
Thanks. How to integrate with Steam API

### ISSUE THREAD

**Issue by jonasrh** [scholtzm/meteor-accounts-steam#1]
Hey. Thanks for this great package.

How would I go around making it so I can read their game library via the Steam API. I saw that this one just grabs the ID, and uses public info - not what we want, as some people will have private accounts.

**Comment by scholtzm** [comment]
You cannot read other user's game library if their profile is private (or friends only).

Here's a list of public API endpoints: https://developer.valvesoftware.com/wiki/Steam_Web_API

**Comment by scholtzm** [comment]
Going to close this since this is not really an issue.
