### ISSUE TITLE
Login simply isn't working

### ISSUE THREAD

**Issue by LethalClips** [scholtzm/meteor-accounts-steam#2]
Hi, this might be a dumb error by me, but I just can't get my login button to do anything. I have a button with a class of "steam-login-button", and have this code in my navbar's script file: 

```
Template.navbar.events({
    'click .steam-login-button': function(){
        Meteor.loginWithSteam({
            loginStyle: 'popup'
        });
        console.log('Login button pressed');
    }
});
```

The console outputs the debug message of "Login button pressed" just fine every time I press the button, but the login does nothing. I don't get any errors thrown, and I have accounts-ui installed. I feel like it's my error overall, but I used the code basically straight from the example. Any help would be appreciated :)

**Comment by scholtzm** [comment]
Perhaps you haven't configured Steam as login service?

btw. If you are using `accounts-ui`, you should be using `loginButtons` helper.

**Comment by LethalClips** [comment]
I had the configuration code inside of my client's navbar setup instead of my server script, I feel stupid now. Sorry for bringing this up =x

Thanks for the help though, and I will use the loginButtons, that seems a bit nicer. Thanks :)

**Comment by scholtzm** [comment]
Also, the `popup` style does not work properly therefore `redirect` style is recommended. I'm not even sure if it's possible with OpenID.

I should probably add this into README.
