### ISSUE TITLE
redirectUrl not working correctly

### ISSUE THREAD

**Issue by sebmorris** [scholtzm/meteor-accounts-steam#5]
Hi

I have a heroku app setup at https://steamlevels.herokuapp.com/ and have the custom domain http://www.steamlevels.com/ setup for the app.

The user can use the site fully at http://www.steamlevels.com/, however when they login, they are redirected back to https://steamlevels.herokuapp.com/ (http://i.imgur.com/WmfjxZN.png) even with the 'redirectUrl' enabled. When i created a new app to test this, redirectUrl did not work either.
`Meteor.loginWithSteam({
               redirectUrl: 'http://steamlevels.com/'
          });`

Any help would be greatly appreciated

**Comment by scholtzm** [comment]
I see you closed this without additional comment. Is this still an issue?

**Comment by sebmorris** [comment]
Nope - just a case of setting heroku's root url. My bad

**Comment by scholtzm** [comment]
In this case, the redirect URL wouldn't have helped anyway.
