### ISSUE TITLE
Redirect to ip instead of domain

### ISSUE THREAD

**Issue by ClockRide** [scholtzm/meteor-accounts-steam#6]
Hi! I have a problem. When I'm trying to login on my website (using domain) it's always redirecting me to {my server's ip}/_oauth/steam and I can't login. I'm using mup(https://github.com/zodern/meteor-up) to deploy my app if it matters. Help me please.

**Comment by scholtzm** [comment]
You might need to set `ROOT_URL`: https://docs.meteor.com/environment-variables.html#ROOT-URL

Discussion here might also help: https://forums.meteor.com/t/accounts-how-to-configure-the-redirect-uri-which-meteor-calls/27770

**Comment by ClockRide** [comment]
@scholtzm, ROOT_URL solved my problem, thank you very much!
